version: '3.7'

services:
  mariadb:
    image: mariadb:latest
    container_name: sample-mariadb
    restart: always
    hostname: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    image: redis:latest
    container_name: sample-redis
    restart: always
    hostname: redis
    ports:
      - 6379:6379